name: flutter_avataaar
description: Flutter wrapper widget for Avataaars API allowing to generate and display avatar images.
repository: https://github.com/frananleo/flutter_avataaar
version: 0.1.14
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.1.0
  flutter_material_pickers: ^3.1.2
  flutter_svg: ^2.0.7
  http: ^1.1.0
  uuid: ^3.0.4
  universal_io: ^2.0.4
  path_provider: ^2.0.9

dev_dependencies:
  lints: ^1.0.1

flutter:
  assets:
    - lib/assets/translations/
    - lib/assets/svg/